name: "quantatrack"

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - dash=2.10.0  
  - pandas=2.2.3  
  - numpy=1.26.4  
  - scikit-learn=1.3.2 
  - matplotlib=3.9.2  
  - jupyterlab=4.2.6 
  - pip=24.3  
  - pyecharts=2.0.8
  - statsmodels=0.14.4
  - pip:
      - dash_bootstrap_components==1.7.1